# Generated by Django 4.2.6 on 2023-10-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_id_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='book_id',
        ),
    ]
