# Generated by Django 4.2.6 on 2023-10-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_isbn_book_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='isbn',
        ),
    ]
