# Generated by Django 4.2.6 on 2023-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('#0', 'rented'), ('#1', 'returned'), ('#2', 'lost'), ('#3', 'delayed')], max_length=2),
        ),
    ]
